### PR TITLE
Add feature #91(Enabling selective import of states)

### PR DESCRIPTION
**Pull request by sudo-panda**
Add dialog in import process to enable selective import of states

### CODE REVIEW

**Comment by pushkalkatara** [comment]
Hi @sudo-panda , i tried to import the following behavior of [prius_in_city](https://github.com/JdeRobot/VisualStates-examples/blob/prius_in_city/prius_in_city/prius_in_city.xml) to use the overtake behavior. But the results are not as desired.

overtake
overtake1

**Comment by sudo-panda** [comment]
On it.

**Comment by sudo-panda** [comment]
Done

**Comment by pushkalkatara** [comment]
The transition is still remaining while importing. We just need the state.
transition

**Comment by sudo-panda** [comment]
That's the issue #109. Going to work on it today.

**Comment by pushkalkatara** [comment]
Oh cool. Let's solve that issue first then proceed with this PR.

**Comment by sudo-panda** [comment]
Ok

**Comment by pushkalkatara** [comment]
Hi @sudo-panda . What is the status of this PR?

**Comment by sudo-panda** [comment]
It's waiting for review.

**Comment by pushkalkatara** [comment]
The PR looks good to me. We are planning a release for VisualStates, meanwhile, we'll keep this PR on this branch and add it for next release. Thanks, @sudo-panda for the PR.

**Comment by pushkalkatara** [comment]
As the feature is being developed on the GSoC development repository, closing this PR.
Reference - https://github.com/TheRoboticsClub/colab-gsoc2019-Baidyanath_Kundu/pull/1

**Pull request closed without merging**
