### PR TITLE
Import Functionality with Namespace Strategy

### LINKED ISSUE #31: Import Display in the root state.
When a new state is imported, it is not drawn on the current scene. If we get in one of the states and move up, we are able to see the newly added state.

### PR DESCRIPTION
**Pull request by pushkalkatara**
## Description
With the following pull request, following functionalities are implemented - 

* Import existing Automata into Developing Automata.
* Global and Local Namespace for every Automata.
* Namespace generation with Developing Automata.
* Namespace generation with Opening Automata.
* Namespace generation with Importing Automata.
* ROS Code Generation with Global and Local Namespace.
* UI to access Global and Local Namespace with Qsicintialla Tabbed UI Design.
* ROS Package for VisualStates
* Support for External ROS Package Messages

## Related Links 
[VisualStates GSoC Development Repository](https://github.com/TheRoboticsClub/colab-gsoc2018-PushkalKatara) 
[VisualStates Tool Development Timeline](https://jderobot.org/Club-PushkalKatara)
[VisualStates Forum](https://developers.jderobot.org/c/visualstates)

## Fixes
#31, #33, #34, #45, #47, #49, #50, #52, #53, #54 
https://github.com/TheRoboticsClub/colab-gsoc2018-PushkalKatara/issues/1
https://github.com/TheRoboticsClub/colab-gsoc2018-PushkalKatara/issues/2
https://github.com/TheRoboticsClub/colab-gsoc2018-PushkalKatara/issues/3 ...
upto  
https://github.com/TheRoboticsClub/colab-gsoc2018-PushkalKatara/issues/29

## Demos and Tests
* [Yolo v3 Deep Learning based Road-Sign Detection and Toyota Car Behavior](https://drive.google.com/open?id=1KhbC-gaEJzpheIcnOgjoHaEhhPgU93Tr)
* [VisualStates as ROS Package](https://www.youtube.com/watch?v=m_CLVPF5Rt4)
* [ToyotaCar Spawn Behavior Example](https://youtu.be/RwC_Ltsav30)
* [ToyotaCar Sensor Data](https://drive.google.com/open?id=1LXy1r210r0ZTlEkOQyMqik07MZhUqsd2)
* [PR2 Robot Sensor Simulation](https://drive.google.com/open?id=1_27RogVlw3FUO1uXcVKrf-DM_lAJE5Uq)

## ToDos
* Tutorial onto Importing Automata
* Tutorial onto using Global and Local Namespaces
* User Documentation on JdeRobot Documentation.
* TurtleBot example video with newly implemented features.
* Toyota Prius Car Stop behavior development using VisualStates and simulation in Gazebo. Stop sign should be detected through image processing based on Yolo algorithm.

### CODE REVIEW

**Comment by okanasik** [comment]
Dear @pushkalkatara, i have merged the master from the original visualstates repo. Can you pull my changes and test it? If everything is fine, I would like to propose some changes on the current implementation. Best,

**Comment by pushkalkatara** [comment]
@okanasik Sir. I have tested the pull as a ros-package with the namespace functionality. The ROS Code generation is failing as the object PythonGenerator is being created instead of PythonROSGenerator. I think as we are delivering it as a ROS Package, PythonROSGenerator object should be created.
Rest everything seems to work fine. Please guide me with the further changes needed. 
Here's the list of some more updates which I think needs to be worked upon.

1.  Global Namespace access from UI
2.  Namespace strategy support with import functionality.
3.  Removing Namespace IDs and Name tag from XML
4.  Developing User example to demonstrate Import Functionality.

**Comment by pushkalkatara** [comment]
With the recent commit, Import automata support Namespace strategy.

**Comment by pushkalkatara** [comment]
With the recent commit, code generation with namespace strategy is fixed. JDECOMM removed as the package is purely based on ROS.

**Comment by okanasik** [comment]
Dear @pushkalkatara, I have checked your code, but there seems to be an error in the code generation. line 292 of pythonrosgenerator.py gives error. Somehow, state.parent returns an integer value, but it is supposed to be either `None` or the parent State of that state. Can you test it?

**Comment by pushkalkatara** [comment]
@okanasik Sir, state.parent returns an integer value '0' in the case when rootState is given as state, in all other cases a state object is returned. On my side, the code is working fine. Can you please reproduce the error.

**Comment by okanasik** [comment]
Firstly, it is not a good practice to assign two different data types to a variable. At once `parent` variable refer to state object and then somehow refer to integer 0. This is not self explanatory. When I see that I might think that state.parent refers to the id of the parent. Therefore, if the state does not have parent, it should have the value of `None`. I understood 0 stands for NULL in C/C++, but it is not good practice even for C/C++. Best.

To reproduce the error follow these steps:
1. create new behavior
2. create two states
3. add a new function using Data -> functions.
4. save the behavior
5. generate python
Then, we get the following error:
```
File "/media/okan/depo/jderobot/pushkal-repo/catkin_ws/src/visualstates/src/visualstates/generators/pythonrosgenerator.py", line 313, in generateMain
    mainStr.append(', state' + str(state.parent.id) + ', gui)\n')
AttributeError: 'NoneType' object has no attribute 'id'
```

Also, I will be reviewing other parts of your contribution in the following day. I might propose further improvements. Overall good work :+1: 

Also, let's make this pull request as the submission of your work for GSoC 2018. Can you edit the description of this pull request to document your work. Please check and follow guidelines here: https://developers.google.com/open-source/gsoc/help/work-product

**Comment by pushkalkatara** [comment]
@okanasik Sir. I noticed while opening exisiting automata through XML, '0' as an int was passed to state.parent of the rootState, instead of None. I have fixed it with the recent commit. Thanks for noticing. Please review and propose further improvements.
I would update the pull request description according to GSoC's guidelines soon. 
Also, this pull request solves issue #49 . Referencing it here.

**Comment by pushkalkatara** [comment]
With the recent commit, Namespace ID and Name tag removed.

**Comment by pushkalkatara** [comment]
With the recent commits, UI for Global namespace is implemented. Also the code generation now supports the namespace generation without ID and Name tags. The generated code looks more presentable.

**Comment by okanasik** [comment]
Nice work @pushkalkatara, but I have a little comments on the UI design. I think we can update the Data menu to have only `Timer, Global Namespace, Local Namespace`. The global namespace UI should be exactly same as local namespace. I like the tabbed UI design. Can you adapt those code editors for the qsicintialla editor with the language selection option?

**Comment by pushkalkatara** [comment]
With the recent commit, Tabbed UI Design with qsicintialla editor is implemented.

**Comment by pushkalkatara** [comment]
Thanks for the merge :+1: :100:

**Pull request merged**
